### PR TITLE
hello world program in java

### PR DESCRIPTION
**Pull request by agrawalharsh90**

### CODE REVIEW

**Comment by achaljhawar** [comment]
@agrawalharsh90 try in any other language java is not avalaible

**Comment by agrawalharsh90** [comment]
Ok

**Comment by agrawalharsh90** [comment]
@achaljhawar in c and python code is already added 
Can I add in C++?

**Comment by achaljhawar** [comment]
yes you can @agrawalharsh90

**Comment by agrawalharsh90** [comment]
@achaljhawar as you mention "try in any other language java is not avalaible" but you accepted another pr of java

**Comment by achaljhawar** [comment]
because he gave it before you @agrawalharsh90

**Comment by achaljhawar** [comment]
And if it hurts you I am really sorry

**Pull request closed without merging**
