### PR TITLE
Update HelloWorld.java

### PR DESCRIPTION
**Pull request by VelamuriPrasad**

### CODE REVIEW

**Comment by achaljhawar** [comment]
hey @VelamuriPrasad hello world in java is done by someone else pls try in other languages.

**Comment by VelamuriPrasad** [comment]
Bro,Once please check i added new Hello World! programs in VBScript, Logo, CoffeScript, Basic, Perl 5, Objective-C Languages, If you like them please merge my pull requests as it will be helpful to me as this is my First Hactoberfest Contest.Thanking You!
    On Thursday, 15 October, 2020, 05:06:00 pm IST, Achal Jhawar <notifications@github.com> wrote:  
 
 


Closed #66.

**Comment by achaljhawar** [comment]
I have merged some of them you can try in more languages

**Comment by VelamuriPrasad** [comment]
Thank you😁On Oct 16, 2020 9:28 AM, Achal Jhawar <notifications@github.com> wrote:
I have merged some of them you can try in more languages

**Pull request closed without merging**
